### ISSUE TITLE
Problem if use parentRootValue

### ISSUE THREAD

**Issue by ArCoLab** [leandrogehlen/yii2-treegrid#21]
I need to show tree of subcategories.
In dataProvider I have all cats tree
I use params:
```
'dataProvider' => $dataProvider,
'keyColumnName' => 'id',
'parentColumnName' => 'parent_id',
'parentRootValue' => 2,
```
parentRootValue= **2** - ID of parent category I need to...
All subcats are showing in right order but expande/collapse and tree-view not working in this case...

**Comment by ArCoLab** [comment]
Without parameter _parentRootValue_ is working fine. But I need use it.

**Comment by leandrogehlen** [comment]
I believe, this is happening because you are not using the master version.
I released the new version to solve this problem

**Comment by jianyan74** [comment]
Where is the new version? the is 1.0.2?

**Comment by jianyan74** [comment]
> 
> 
> I believe, this is happening because you are not using the master version.
> I released the new version to solve this problem

Where is the new version? the is 1.0.2?

**Comment by leandrogehlen** [comment]
@jianyan74 this post is old. The version 1.0.2 is the master version right now.
But there are break changes in this version, I willl rename version form 1.0.2 to 1.1.0

**Comment by tebachekhaled** [comment]
i have the same problem and i trayed to fix it by changing the vervion but the problem is not solved Without parameter parentRootValue is working fine
